#!/usr/bin/env python

from canari.commands.common import canari_main
from canari.commands import * # Do not remove this line. It loads all our sub-commands into the main commander.


__author__ = 'Nadeem Douba'
__copyright__ = 'Copyright 2012, Canari Project'
__credits__ = []

__license__ = 'GPL'
__version__ = '0.2'
__maintainer__ = 'Nadeem Douba'
__email__ = 'ndouba@gmail.com'
__status__ = 'Development'


if __name__ == '__main__':
    try:
        canari_main()
    except KeyboardInterrupt:
        print('exiting...')
        pass