#!/usr/bin/env python
from canari.commands.common import fix_pypath, fix_binpath

from canari.commands.run_transform import run_transform
from canari.config import config

__author__ = 'Nadeem Douba'
__copyright__ = 'Copyright 2012, Canari Project'
__credits__ = []

__license__ = 'GPL'
__version__ = '0.1'
__maintainer__ = 'Nadeem Douba'
__email__ = 'ndouba@gmail.com'
__status__ = 'Development'


if __name__ == '__main__':
    fix_pypath()
    fix_binpath(config['default/path'])
    run_transform.parser.prog = 'dispatcher'
    opts = run_transform.parser.parse_args()
    run_transform(opts)
