#!/usr/bin/env python

import sys
import subprocess

from canari.utils.fs import fmutex
from canari.easygui import passwordbox

__author__ = 'Nadeem Douba'
__copyright__ = 'Copyright 2012, Canari Project'
__credits__ = []

__license__ = 'GPL'
__version__ = '0.3'
__maintainer__ = 'Nadeem Douba'
__email__ = 'ndouba@gmail.com'
__status__ = 'Development'


def main():

    if not sys.argv[1:]:
        print 'usage: %s <command>' % sys.argv[0]
        exit(-1)


    p = subprocess.Popen(['sudo', '-S'] + sys.argv[1:], stdin=subprocess.PIPE, stderr=subprocess.PIPE)
    p.communicate()

    if not p.returncode:
        exit(0)

    l = fmutex('pysudo.lock')
    for i in range(0, 3):
        password = passwordbox('Please enter your password.', 'sudo', '')
        if password is None:
            exit(1)
        p = subprocess.Popen(['sudo', '-S', 'true'], stdin=subprocess.PIPE)
        p.communicate(input='%s\n' % password)
        if not p.returncode:
            l.unlock()
            p = subprocess.Popen(['sudo', '-S'] + sys.argv[1:])
            p.communicate()
            exit(p.returncode)
    exit(2)

if __name__ == '__main__':
    main()
